name: CI
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GasPriceConverter
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: envsubst < wwwroot/appsettings.json.tmpl > wwwroot/appsettings.json
        env:
          CURRENCY_FREAKS_API_KEY: ${{ secrets.CURRENCY_FREAKS_API_KEY }}
      - run: dotnet publish -c Release -o release
      - run: |
          sed -i 's/<base href="\/" \/>/<base href="\/gas-price-converter\/" \/>/g' release/wwwroot/index.html
          touch release/wwwroot/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: release/wwwroot
